### ISSUE TITLE
Bug/ handle default response from AAVE correctly

### ISSUE THREAD

**Issue by kKaskak** [PetromirDev/safe-hawk#23]
Currently when there is a collateral but no loan on a specific network we show a default response with 
score -- 1.15 and a bad indicator. 
Instead we should show a message: 
 - `You dont have any loans on ${network}`
 
 To debug this use `0x4F3c11ac6f552E36211661d161360e4A7677C683` and try switching to base network

**Comment by PetromirDev** [comment]
Fixed
